# Copyright 2021 The LevelDB Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. See the AUTHORS file for names of contributors.

name: ci-android
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
      # 你可以根据需求改为 'Release' 或 'Debug'
      CMAKE_BUILD_TYPE: RelWithDebInfo 
      # 目标安卓架构，常见有：arm64-v8a, armeabi-v7a, x86_64, x86
      ANDROID_ABI: arm64-v8a
      # 最低支持的 Android API Level
      ANDROID_PLATFORM: android-21

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    # GitHub Hosted Runner (ubuntu-latest) 自带了 Android NDK，我们可以直接通过环境变量获取路径
    - name: Setup Android NDK Path
      run: |
        echo "ANDROID_NDK_HOME=${ANDROID_NDK_LATEST_HOME}" >> $GITHUB_ENV

    - name: Generate build config
      run: >-
        cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}"
        -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}
        -DCMAKE_TOOLCHAIN_FILE="${{ env.ANDROID_NDK_HOME }}/build/cmake/android.toolchain.cmake"
        -DANDROID_ABI=${{ env.ANDROID_ABI }}
        -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }}
        -DLEVELDB_BUILD_TESTS=OFF
        -DLEVELDB_BUILD_BENCHMARKS=OFF

    - name: Build
      run: >-
        cmake --build "${{ env.CMAKE_BUILD_DIR }}"
        --config "${{ env.CMAKE_BUILD_TYPE }}"
